//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSCVRCWiz {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class emojiSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static emojiSettings defaultInstance = ((emojiSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new emojiSettings())));
        
        public static emojiSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cry emoji")]
        public string emoji1 {
            get {
                return ((string)(this["emoji1"]));
            }
            set {
                this["emoji1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Glasses emoji")]
        public string emoji2 {
            get {
                return ((string)(this["emoji2"]));
            }
            set {
                this["emoji2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Heart face emoji")]
        public string emoji3 {
            get {
                return ((string)(this["emoji3"]));
            }
            set {
                this["emoji3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Roxy")]
        public string emoji4 {
            get {
                return ((string)(this["emoji4"]));
            }
            set {
                this["emoji4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua cry")]
        public string emoji5 {
            get {
                return ((string)(this["emoji5"]));
            }
            set {
                this["emoji5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thumbs Up")]
        public string emoji6 {
            get {
                return ((string)(this["emoji6"]));
            }
            set {
                this["emoji6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Confused ")]
        public string emoji7 {
            get {
                return ((string)(this["emoji7"]));
            }
            set {
                this["emoji7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Angry")]
        public string emoji8 {
            get {
                return ((string)(this["emoji8"]));
            }
            set {
                this["emoji8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Laugh")]
        public string emoji9 {
            get {
                return ((string)(this["emoji9"]));
            }
            set {
                this["emoji9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poggers")]
        public string emoji10 {
            get {
                return ((string)(this["emoji10"]));
            }
            set {
                this["emoji10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extra11")]
        public string emoji11 {
            get {
                return ((string)(this["emoji11"]));
            }
            set {
                this["emoji11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extra12")]
        public string emoji12 {
            get {
                return ((string)(this["emoji12"]));
            }
            set {
                this["emoji12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extra13")]
        public string emoji13 {
            get {
                return ((string)(this["emoji13"]));
            }
            set {
                this["emoji13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extra14")]
        public string emoji14 {
            get {
                return ((string)(this["emoji14"]));
            }
            set {
                this["emoji14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extra15")]
        public string emoji15 {
            get {
                return ((string)(this["emoji15"]));
            }
            set {
                this["emoji15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extra16")]
        public string emoji16 {
            get {
                return ((string)(this["emoji16"]));
            }
            set {
                this["emoji16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extra17")]
        public string emoji17 {
            get {
                return ((string)(this["emoji17"]));
            }
            set {
                this["emoji17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extra18")]
        public string emoji18 {
            get {
                return ((string)(this["emoji18"]));
            }
            set {
                this["emoji18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extra19")]
        public string emoji19 {
            get {
                return ((string)(this["emoji19"]));
            }
            set {
                this["emoji19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extra20")]
        public string emoji20 {
            get {
                return ((string)(this["emoji20"]));
            }
            set {
                this["emoji20"] = value;
            }
        }
    }
}
