//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSCVRCWiz.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string yourKey {
            get {
                return ((string)(this["yourKey"]));
            }
            set {
                this["yourKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eastus")]
        public string yourRegion {
            get {
                return ((string)(this["yourRegion"]));
            }
            set {
                this["yourRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool remember {
            get {
                return ((bool)(this["remember"]));
            }
            set {
                this["remember"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool recognition {
            get {
                return ((bool)(this["recognition"]));
            }
            set {
                this["recognition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("begin quoting me")]
        public string activationWord {
            get {
                return ((string)(this["activationWord"]));
            }
            set {
                this["activationWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string delayDebugValueSetting {
            get {
                return ((string)(this["delayDebugValueSetting"]));
            }
            set {
                this["delayDebugValueSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool profanityFilterSetting {
            get {
                return ((bool)(this["profanityFilterSetting"]));
            }
            set {
                this["profanityFilterSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool logOrNotSetting {
            get {
                return ((bool)(this["logOrNotSetting"]));
            }
            set {
                this["logOrNotSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sendOSCSetting {
            get {
                return ((bool)(this["sendOSCSetting"]));
            }
            set {
                this["sendOSCSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool clearTTSWindowSetting {
            get {
                return ((bool)(this["clearTTSWindowSetting"]));
            }
            set {
                this["clearTTSWindowSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alwaysTopSetting {
            get {
                return ((bool)(this["alwaysTopSetting"]));
            }
            set {
                this["alwaysTopSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool disableTTSSetting {
            get {
                return ((bool)(this["disableTTSSetting"]));
            }
            set {
                this["disableTTSSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hideDelaySetting {
            get {
                return ((bool)(this["hideDelaySetting"]));
            }
            set {
                this["hideDelaySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string hideDelayValue {
            get {
                return ((string)(this["hideDelayValue"]));
            }
            set {
                this["hideDelayValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wordsTranslateVRCSetting {
            get {
                return ((bool)(this["wordsTranslateVRCSetting"]));
            }
            set {
                this["wordsTranslateVRCSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool phraseListBoolSetting {
            get {
                return ((bool)(this["phraseListBoolSetting"]));
            }
            set {
                this["phraseListBoolSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jessie,Jakob,")]
        public string phraseListValue {
            get {
                return ((string)(this["phraseListValue"]));
            }
            set {
                this["phraseListValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SyncParaValue {
            get {
                return ((int)(this["SyncParaValue"]));
            }
            set {
                this["SyncParaValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string MicName {
            get {
                return ((string)(this["MicName"]));
            }
            set {
                this["MicName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string SpeakerName {
            get {
                return ((string)(this["SpeakerName"]));
            }
            set {
                this["SpeakerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectSpot {
            get {
                return ((bool)(this["ConnectSpot"]));
            }
            set {
                this["ConnectSpot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PKCERefreshToken {
            get {
                return ((string)(this["PKCERefreshToken"]));
            }
            set {
                this["PKCERefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PKCEAccessToken {
            get {
                return ((string)(this["PKCEAccessToken"]));
            }
            set {
                this["PKCEAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EmojiSetting {
            get {
                return ((bool)(this["EmojiSetting"]));
            }
            set {
                this["EmojiSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpotifyOutputSetting {
            get {
                return ((bool)(this["SpotifyOutputSetting"]));
            }
            set {
                this["SpotifyOutputSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string HRIntervalSetting {
            get {
                return ((string)(this["HRIntervalSetting"]));
            }
            set {
                this["HRIntervalSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4026")]
        public string HRPortSetting {
            get {
                return ((string)(this["HRPortSetting"]));
            }
            set {
                this["HRPortSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BPMSpamSetting {
            get {
                return ((bool)(this["BPMSpamSetting"]));
            }
            set {
                this["BPMSpamSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int voiceBoxSetting {
            get {
                return ((int)(this["voiceBoxSetting"]));
            }
            set {
                this["voiceBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int styleBoxSetting {
            get {
                return ((int)(this["styleBoxSetting"]));
            }
            set {
                this["styleBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int langToBoxSetting {
            get {
                return ((int)(this["langToBoxSetting"]));
            }
            set {
                this["langToBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int langSpokenSetting {
            get {
                return ((int)(this["langSpokenSetting"]));
            }
            set {
                this["langSpokenSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int pitchSetting {
            get {
                return ((int)(this["pitchSetting"]));
            }
            set {
                this["pitchSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int volumeSetting {
            get {
                return ((int)(this["volumeSetting"]));
            }
            set {
                this["volumeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int rateSetting {
            get {
                return ((int)(this["rateSetting"]));
            }
            set {
                this["rateSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool STTTSContinuous {
            get {
                return ((bool)(this["STTTSContinuous"]));
            }
            set {
                this["STTTSContinuous"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useBuiltInSetting {
            get {
                return ((bool)(this["useBuiltInSetting"]));
            }
            set {
                this["useBuiltInSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BuiltInVoiceSetting {
            get {
                return ((int)(this["BuiltInVoiceSetting"]));
            }
            set {
                this["BuiltInVoiceSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BuiltInOutputSetting {
            get {
                return ((string)(this["BuiltInOutputSetting"]));
            }
            set {
                this["BuiltInOutputSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpotifyPeriodicallySetting {
            get {
                return ((bool)(this["SpotifyPeriodicallySetting"]));
            }
            set {
                this["SpotifyPeriodicallySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpotifySpamSetting {
            get {
                return ((bool)(this["SpotifySpamSetting"]));
            }
            set {
                this["SpotifySpamSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string SpotifyTimerIntervalSetting {
            get {
                return ((string)(this["SpotifyTimerIntervalSetting"]));
            }
            set {
                this["SpotifyTimerIntervalSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioCancelSetting {
            get {
                return ((bool)(this["AudioCancelSetting"]));
            }
            set {
                this["AudioCancelSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cultureInfoSetting {
            get {
                return ((string)(this["cultureInfoSetting"]));
            }
            set {
                this["cultureInfoSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bannerSetting {
            get {
                return ((bool)(this["bannerSetting"]));
            }
            set {
                this["bannerSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpotifyLegacySetting {
            get {
                return ((bool)(this["SpotifyLegacySetting"]));
            }
            set {
                this["SpotifyLegacySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpotifyKey {
            get {
                return ((string)(this["SpotifyKey"]));
            }
            set {
                this["SpotifyKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendVRCChatBoxSetting {
            get {
                return ((bool)(this["SendVRCChatBoxSetting"]));
            }
            set {
                this["SendVRCChatBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChatBoxKeyboardSetting {
            get {
                return ((bool)(this["ChatBoxKeyboardSetting"]));
            }
            set {
                this["ChatBoxKeyboardSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool minimizeToolBarSetting {
            get {
                return ((bool)(this["minimizeToolBarSetting"]));
            }
            set {
                this["minimizeToolBarSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public string fontSizeSetting {
            get {
                return ((string)(this["fontSizeSetting"]));
            }
            set {
                this["fontSizeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GreenScreenSetting {
            get {
                return ((bool)(this["GreenScreenSetting"]));
            }
            set {
                this["GreenScreenSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'{title}\' - \'{artist}\'")]
        public string SpotifyCustomSetting {
            get {
                return ((string)(this["SpotifyCustomSetting"]));
            }
            set {
                this["SpotifyCustomSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VRCSoundNotifySetting {
            get {
                return ((bool)(this["VRCSoundNotifySetting"]));
            }
            set {
                this["VRCSoundNotifySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SystemTraySetting {
            get {
                return ((bool)(this["SystemTraySetting"]));
            }
            set {
                this["SystemTraySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool playMediaSetting {
            get {
                return ((bool)(this["playMediaSetting"]));
            }
            set {
                this["playMediaSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VRCUseDelay {
            get {
                return ((bool)(this["VRCUseDelay"]));
            }
            set {
                this["VRCUseDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int voiceLanguage {
            get {
                return ((int)(this["voiceLanguage"]));
            }
            set {
                this["voiceLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WebcaptionerSetting {
            get {
                return ((bool)(this["WebcaptionerSetting"]));
            }
            set {
                this["WebcaptionerSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool activateOSCStart {
            get {
                return ((bool)(this["activateOSCStart"]));
            }
            set {
                this["activateOSCStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool independentSpotifyText {
            get {
                return ((bool)(this["independentSpotifyText"]));
            }
            set {
                this["independentSpotifyText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string rememberAddress {
            get {
                return ((string)(this["rememberAddress"]));
            }
            set {
                this["rememberAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9000")]
        public string rememberPort {
            get {
                return ((string)(this["rememberPort"]));
            }
            set {
                this["rememberPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveUseAzure {
            get {
                return ((bool)(this["saveUseAzure"]));
            }
            set {
                this["saveUseAzure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveUseSystem {
            get {
                return ((bool)(this["saveUseSystem"]));
            }
            set {
                this["saveUseSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chatBoxSpotifyOnly {
            get {
                return ((bool)(this["chatBoxSpotifyOnly"]));
            }
            set {
                this["chatBoxSpotifyOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpotifyNoUseKat {
            get {
                return ((bool)(this["SpotifyNoUseKat"]));
            }
            set {
                this["SpotifyNoUseKat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpotifyNoUseChatbox {
            get {
                return ((bool)(this["SpotifyNoUseChatbox"]));
            }
            set {
                this["SpotifyNoUseChatbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chatBoxSpotifyOnly4VRC {
            get {
                return ((bool)(this["chatBoxSpotifyOnly4VRC"]));
            }
            set {
                this["chatBoxSpotifyOnly4VRC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool heartrateOutput {
            get {
                return ((bool)(this["heartrateOutput"]));
            }
            set {
                this["heartrateOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableMedia {
            get {
                return ((bool)(this["enableMedia"]));
            }
            set {
                this["enableMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System Speech")]
        public string ttsMode {
            get {
                return ((string)(this["ttsMode"]));
            }
            set {
                this["ttsMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Spotify.exe,")]
        public string approvedSource {
            get {
                return ((string)(this["approvedSource"]));
            }
            set {
                this["approvedSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StopOnPause {
            get {
                return ((bool)(this["StopOnPause"]));
            }
            set {
                this["StopOnPause"] = value;
            }
        }
    }
}
