//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSCVRCWiz.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string yourKey {
            get {
                return ((string)(this["yourKey"]));
            }
            set {
                this["yourKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eastus")]
        public string yourRegion {
            get {
                return ((string)(this["yourRegion"]));
            }
            set {
                this["yourRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool remember {
            get {
                return ((bool)(this["remember"]));
            }
            set {
                this["remember"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool recognition {
            get {
                return ((bool)(this["recognition"]));
            }
            set {
                this["recognition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("begin quoting me")]
        public string activationWord {
            get {
                return ((string)(this["activationWord"]));
            }
            set {
                this["activationWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string delayDebugValueSetting {
            get {
                return ((string)(this["delayDebugValueSetting"]));
            }
            set {
                this["delayDebugValueSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool profanityFilterSetting {
            get {
                return ((bool)(this["profanityFilterSetting"]));
            }
            set {
                this["profanityFilterSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool logOrNotSetting {
            get {
                return ((bool)(this["logOrNotSetting"]));
            }
            set {
                this["logOrNotSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sendOSCSetting {
            get {
                return ((bool)(this["sendOSCSetting"]));
            }
            set {
                this["sendOSCSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool clearTTSWindowSetting {
            get {
                return ((bool)(this["clearTTSWindowSetting"]));
            }
            set {
                this["clearTTSWindowSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alwaysTopSetting {
            get {
                return ((bool)(this["alwaysTopSetting"]));
            }
            set {
                this["alwaysTopSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool disableTTSSetting {
            get {
                return ((bool)(this["disableTTSSetting"]));
            }
            set {
                this["disableTTSSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hideDelaySetting {
            get {
                return ((bool)(this["hideDelaySetting"]));
            }
            set {
                this["hideDelaySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string hideDelayValue {
            get {
                return ((string)(this["hideDelayValue"]));
            }
            set {
                this["hideDelayValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wordsTranslateVRCSetting {
            get {
                return ((bool)(this["wordsTranslateVRCSetting"]));
            }
            set {
                this["wordsTranslateVRCSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool phraseListBoolSetting {
            get {
                return ((bool)(this["phraseListBoolSetting"]));
            }
            set {
                this["phraseListBoolSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jessie,Jakob,")]
        public string phraseListValue {
            get {
                return ((string)(this["phraseListValue"]));
            }
            set {
                this["phraseListValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SyncParaValue {
            get {
                return ((int)(this["SyncParaValue"]));
            }
            set {
                this["SyncParaValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string MicName {
            get {
                return ((string)(this["MicName"]));
            }
            set {
                this["MicName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string SpeakerName {
            get {
                return ((string)(this["SpeakerName"]));
            }
            set {
                this["SpeakerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectSpot {
            get {
                return ((bool)(this["ConnectSpot"]));
            }
            set {
                this["ConnectSpot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PKCERefreshToken {
            get {
                return ((string)(this["PKCERefreshToken"]));
            }
            set {
                this["PKCERefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PKCEAccessToken {
            get {
                return ((string)(this["PKCEAccessToken"]));
            }
            set {
                this["PKCEAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EmojiSetting {
            get {
                return ((bool)(this["EmojiSetting"]));
            }
            set {
                this["EmojiSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpotifyOutputSetting {
            get {
                return ((bool)(this["SpotifyOutputSetting"]));
            }
            set {
                this["SpotifyOutputSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string HRIntervalSetting {
            get {
                return ((string)(this["HRIntervalSetting"]));
            }
            set {
                this["HRIntervalSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4026")]
        public string HRPortSetting {
            get {
                return ((string)(this["HRPortSetting"]));
            }
            set {
                this["HRPortSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BPMSpamSetting {
            get {
                return ((bool)(this["BPMSpamSetting"]));
            }
            set {
                this["BPMSpamSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int voiceBoxSetting {
            get {
                return ((int)(this["voiceBoxSetting"]));
            }
            set {
                this["voiceBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int styleBoxSetting {
            get {
                return ((int)(this["styleBoxSetting"]));
            }
            set {
                this["styleBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int langToBoxSetting {
            get {
                return ((int)(this["langToBoxSetting"]));
            }
            set {
                this["langToBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int langSpokenSetting {
            get {
                return ((int)(this["langSpokenSetting"]));
            }
            set {
                this["langSpokenSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int pitchSetting {
            get {
                return ((int)(this["pitchSetting"]));
            }
            set {
                this["pitchSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int volumeSetting {
            get {
                return ((int)(this["volumeSetting"]));
            }
            set {
                this["volumeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int rateSetting {
            get {
                return ((int)(this["rateSetting"]));
            }
            set {
                this["rateSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool STTTSContinuous {
            get {
                return ((bool)(this["STTTSContinuous"]));
            }
            set {
                this["STTTSContinuous"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useBuiltInSetting {
            get {
                return ((bool)(this["useBuiltInSetting"]));
            }
            set {
                this["useBuiltInSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BuiltInVoiceSetting {
            get {
                return ((int)(this["BuiltInVoiceSetting"]));
            }
            set {
                this["BuiltInVoiceSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BuiltInOutputSetting {
            get {
                return ((string)(this["BuiltInOutputSetting"]));
            }
            set {
                this["BuiltInOutputSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpotifyPeriodicallySetting {
            get {
                return ((bool)(this["SpotifyPeriodicallySetting"]));
            }
            set {
                this["SpotifyPeriodicallySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpotifySpamSetting {
            get {
                return ((bool)(this["SpotifySpamSetting"]));
            }
            set {
                this["SpotifySpamSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string SpotifyTimerIntervalSetting {
            get {
                return ((string)(this["SpotifyTimerIntervalSetting"]));
            }
            set {
                this["SpotifyTimerIntervalSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioCancelSetting {
            get {
                return ((bool)(this["AudioCancelSetting"]));
            }
            set {
                this["AudioCancelSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cultureInfoSetting {
            get {
                return ((string)(this["cultureInfoSetting"]));
            }
            set {
                this["cultureInfoSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bannerSetting {
            get {
                return ((bool)(this["bannerSetting"]));
            }
            set {
                this["bannerSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpotifyLegacySetting {
            get {
                return ((bool)(this["SpotifyLegacySetting"]));
            }
            set {
                this["SpotifyLegacySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpotifyKey {
            get {
                return ((string)(this["SpotifyKey"]));
            }
            set {
                this["SpotifyKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendVRCChatBoxSetting {
            get {
                return ((bool)(this["SendVRCChatBoxSetting"]));
            }
            set {
                this["SendVRCChatBoxSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChatBoxKeyboardSetting {
            get {
                return ((bool)(this["ChatBoxKeyboardSetting"]));
            }
            set {
                this["ChatBoxKeyboardSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool minimizeToolBarSetting {
            get {
                return ((bool)(this["minimizeToolBarSetting"]));
            }
            set {
                this["minimizeToolBarSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public string fontSizeSetting {
            get {
                return ((string)(this["fontSizeSetting"]));
            }
            set {
                this["fontSizeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GreenScreenSetting {
            get {
                return ((bool)(this["GreenScreenSetting"]));
            }
            set {
                this["GreenScreenSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{pause} {title} - {artist} ")]
        public string SpotifyCustomSetting {
            get {
                return ((string)(this["SpotifyCustomSetting"]));
            }
            set {
                this["SpotifyCustomSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VRCSoundNotifySetting {
            get {
                return ((bool)(this["VRCSoundNotifySetting"]));
            }
            set {
                this["VRCSoundNotifySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SystemTraySetting {
            get {
                return ((bool)(this["SystemTraySetting"]));
            }
            set {
                this["SystemTraySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool playMediaSetting {
            get {
                return ((bool)(this["playMediaSetting"]));
            }
            set {
                this["playMediaSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VRCUseDelay {
            get {
                return ((bool)(this["VRCUseDelay"]));
            }
            set {
                this["VRCUseDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int voiceLanguage {
            get {
                return ((int)(this["voiceLanguage"]));
            }
            set {
                this["voiceLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WebcaptionerSetting {
            get {
                return ((bool)(this["WebcaptionerSetting"]));
            }
            set {
                this["WebcaptionerSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool activateOSCStart {
            get {
                return ((bool)(this["activateOSCStart"]));
            }
            set {
                this["activateOSCStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool independentSpotifyText {
            get {
                return ((bool)(this["independentSpotifyText"]));
            }
            set {
                this["independentSpotifyText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string rememberAddress {
            get {
                return ((string)(this["rememberAddress"]));
            }
            set {
                this["rememberAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9000")]
        public string rememberPort {
            get {
                return ((string)(this["rememberPort"]));
            }
            set {
                this["rememberPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveUseAzure {
            get {
                return ((bool)(this["saveUseAzure"]));
            }
            set {
                this["saveUseAzure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveUseSystem {
            get {
                return ((bool)(this["saveUseSystem"]));
            }
            set {
                this["saveUseSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chatBoxSpotifyOnly {
            get {
                return ((bool)(this["chatBoxSpotifyOnly"]));
            }
            set {
                this["chatBoxSpotifyOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpotifyNoUseKat {
            get {
                return ((bool)(this["SpotifyNoUseKat"]));
            }
            set {
                this["SpotifyNoUseKat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpotifyNoUseChatbox {
            get {
                return ((bool)(this["SpotifyNoUseChatbox"]));
            }
            set {
                this["SpotifyNoUseChatbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chatBoxSpotifyOnly4VRC {
            get {
                return ((bool)(this["chatBoxSpotifyOnly4VRC"]));
            }
            set {
                this["chatBoxSpotifyOnly4VRC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool heartrateOutput {
            get {
                return ((bool)(this["heartrateOutput"]));
            }
            set {
                this["heartrateOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableMedia {
            get {
                return ((bool)(this["enableMedia"]));
            }
            set {
                this["enableMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TikTok")]
        public string ttsMode {
            get {
                return ((string)(this["ttsMode"]));
            }
            set {
                this["ttsMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string approvedSource {
            get {
                return ((string)(this["approvedSource"]));
            }
            set {
                this["approvedSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StopOnPause {
            get {
                return ((bool)(this["StopOnPause"]));
            }
            set {
                this["StopOnPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string voiceCommandList {
            get {
                return ((string)(this["voiceCommandList"]));
            }
            set {
                this["voiceCommandList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveDarkMode {
            get {
                return ((bool)(this["saveDarkMode"]));
            }
            set {
                this["saveDarkMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveVoiceActStyle {
            get {
                return ((bool)(this["saveVoiceActStyle"]));
            }
            set {
                this["saveVoiceActStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Whisper")]
        public string STTModeSave {
            get {
                return ((string)(this["STTModeSave"]));
            }
            set {
                this["STTModeSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no folder selected")]
        public string modelnamesave {
            get {
                return ((string)(this["modelnamesave"]));
            }
            set {
                this["modelnamesave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string deepLKeysave {
            get {
                return ((string)(this["deepLKeysave"]));
            }
            set {
                this["deepLKeysave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string OSCAddress {
            get {
                return ((string)(this["OSCAddress"]));
            }
            set {
                this["OSCAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9000")]
        public string OSCPort {
            get {
                return ((string)(this["OSCPort"]));
            }
            set {
                this["OSCPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveToast {
            get {
                return ((bool)(this["saveToast"]));
            }
            set {
                this["saveToast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string presetSave {
            get {
                return ((string)(this["presetSave"]));
            }
            set {
                this["presetSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/avatar/parameters/osc_discord_band")]
        public string discordParaSave {
            get {
                return ((string)(this["discordParaSave"]));
            }
            set {
                this["discordParaSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string discordTimerSave {
            get {
                return ((string)(this["discordTimerSave"]));
            }
            set {
                this["discordTimerSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string replaceSave {
            get {
                return ((string)(this["replaceSave"]));
            }
            set {
                this["replaceSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool wordReplaceBeforeTTS {
            get {
                return ((bool)(this["wordReplaceBeforeTTS"]));
            }
            set {
                this["wordReplaceBeforeTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string emojiNewSave {
            get {
                return ((string)(this["emojiNewSave"]));
            }
            set {
                this["emojiNewSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hotketSave {
            get {
                return ((bool)(this["hotketSave"]));
            }
            set {
                this["hotketSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveAutoRefreshKat {
            get {
                return ((bool)(this["saveAutoRefreshKat"]));
            }
            set {
                this["saveAutoRefreshKat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string normalHotKey {
            get {
                return ((string)(this["normalHotKey"]));
            }
            set {
                this["normalHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public string modHotKey {
            get {
                return ((string)(this["modHotKey"]));
            }
            set {
                this["modHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string yourAWSKey {
            get {
                return ((string)(this["yourAWSKey"]));
            }
            set {
                this["yourAWSKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string yourAWSSecret {
            get {
                return ((string)(this["yourAWSSecret"]));
            }
            set {
                this["yourAWSSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("us-east-1")]
        public string yourAWSRegion {
            get {
                return ((string)(this["yourAWSRegion"]));
            }
            set {
                this["yourAWSRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string elevenLabsAPIKey {
            get {
                return ((string)(this["elevenLabsAPIKey"]));
            }
            set {
                this["elevenLabsAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no model selected")]
        public string whisperModel {
            get {
                return ((string)(this["whisperModel"]));
            }
            set {
                this["whisperModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VRCListemOnStart {
            get {
                return ((bool)(this["VRCListemOnStart"]));
            }
            set {
                this["VRCListemOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VRCSpamLog {
            get {
                return ((bool)(this["VRCSpamLog"]));
            }
            set {
                this["VRCSpamLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VRCAFK {
            get {
                return ((bool)(this["VRCAFK"]));
            }
            set {
                this["VRCAFK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9001")]
        public string VRCPort {
            get {
                return ((string)(this["VRCPort"]));
            }
            set {
                this["VRCPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AFK for {time} minutes")]
        public string AFKMsg {
            get {
                return ((string)(this["AFKMsg"]));
            }
            set {
                this["AFKMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/avatar/parameters/Boop")]
        public string Counter1Para {
            get {
                return ((string)(this["Counter1Para"]));
            }
            set {
                this["Counter1Para"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/avatar/parameters/HighFive")]
        public string Counter2Para {
            get {
                return ((string)(this["Counter2Para"]));
            }
            set {
                this["Counter2Para"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/avatar/parameters/Bonk")]
        public string Counter3Para {
            get {
                return ((string)(this["Counter3Para"]));
            }
            set {
                this["Counter3Para"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/avatar/parameters/Slap")]
        public string Counter4Para {
            get {
                return ((string)(this["Counter4Para"]));
            }
            set {
                this["Counter4Para"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times Booped: {counter}")]
        public string Counter1Msg {
            get {
                return ((string)(this["Counter1Msg"]));
            }
            set {
                this["Counter1Msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HighFive Counter: {counter}")]
        public string Counter2Msg {
            get {
                return ((string)(this["Counter2Msg"]));
            }
            set {
                this["Counter2Msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times Bonked: {counter}")]
        public string Counter3Msg {
            get {
                return ((string)(this["Counter3Msg"]));
            }
            set {
                this["Counter3Msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times Slapped: {counter}")]
        public string Counter4Msg {
            get {
                return ((string)(this["Counter4Msg"]));
            }
            set {
                this["Counter4Msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VRCOnRecieve {
            get {
                return ((bool)(this["VRCOnRecieve"]));
            }
            set {
                this["VRCOnRecieve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OBS4Media {
            get {
                return ((bool)(this["OBS4Media"]));
            }
            set {
                this["OBS4Media"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OBSTextFile {
            get {
                return ((bool)(this["OBSTextFile"]));
            }
            set {
                this["OBSTextFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/avatar/parameters/Something")]
        public string Counter5Para {
            get {
                return ((string)(this["Counter5Para"]));
            }
            set {
                this["Counter5Para"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/avatar/parameters/AnothaOne")]
        public string Counter6Para {
            get {
                return ((string)(this["Counter6Para"]));
            }
            set {
                this["Counter6Para"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Counter: {counter}")]
        public string Counter5Msg {
            get {
                return ((string)(this["Counter5Msg"]));
            }
            set {
                this["Counter5Msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Counter: {counter}")]
        public string Counter6Msg {
            get {
                return ((string)(this["Counter6Msg"]));
            }
            set {
                this["Counter6Msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveCounter {
            get {
                return ((bool)(this["SaveCounter"]));
            }
            set {
                this["SaveCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Counter1 {
            get {
                return ((int)(this["Counter1"]));
            }
            set {
                this["Counter1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Counter2 {
            get {
                return ((int)(this["Counter2"]));
            }
            set {
                this["Counter2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Counter3 {
            get {
                return ((int)(this["Counter3"]));
            }
            set {
                this["Counter3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Counter4 {
            get {
                return ((int)(this["Counter4"]));
            }
            set {
                this["Counter4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Counter5 {
            get {
                return ((int)(this["Counter5"]));
            }
            set {
                this["Counter5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Counter6 {
            get {
                return ((int)(this["Counter6"]));
            }
            set {
                this["Counter6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FilterNoiseWhisper {
            get {
                return ((bool)(this["FilterNoiseWhisper"]));
            }
            set {
                this["FilterNoiseWhisper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string modHotkeyStop {
            get {
                return ((string)(this["modHotkeyStop"]));
            }
            set {
                this["modHotkeyStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string normalHotkeyStop {
            get {
                return ((string)(this["normalHotkeyStop"]));
            }
            set {
                this["normalHotkeyStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowsMediaDisable {
            get {
                return ((bool)(this["WindowsMediaDisable"]));
            }
            set {
                this["WindowsMediaDisable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string SpeakerName2 {
            get {
                return ((string)(this["SpeakerName2"]));
            }
            set {
                this["SpeakerName2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int pitchNew {
            get {
                return ((int)(this["pitchNew"]));
            }
            set {
                this["pitchNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int volumeNew {
            get {
                return ((int)(this["volumeNew"]));
            }
            set {
                this["volumeNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int speedNew {
            get {
                return ((int)(this["speedNew"]));
            }
            set {
                this["speedNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool use2ndDevice {
            get {
                return ((bool)(this["use2ndDevice"]));
            }
            set {
                this["use2ndDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool forwardData {
            get {
                return ((bool)(this["forwardData"]));
            }
            set {
                this["forwardData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string minDuration {
            get {
                return ((string)(this["minDuration"]));
            }
            set {
                this["minDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.0")]
        public string maxDuration {
            get {
                return ((string)(this["maxDuration"]));
            }
            set {
                this["maxDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public string dropStartSilence {
            get {
                return ((string)(this["dropStartSilence"]));
            }
            set {
                this["dropStartSilence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string pauseDuration {
            get {
                return ((string)(this["pauseDuration"]));
            }
            set {
                this["pauseDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool aprilFools2023 {
            get {
                return ((bool)(this["aprilFools2023"]));
            }
            set {
                this["aprilFools2023"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ggml-tiny.bin (75 MB)")]
        public string modelSelected {
            get {
                return ((string)(this["modelSelected"]));
            }
            set {
                this["modelSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int fontSize {
            get {
                return ((int)(this["fontSize"]));
            }
            set {
                this["fontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string delayBeforeNewTTS {
            get {
                return ((string)(this["delayBeforeNewTTS"]));
            }
            set {
                this["delayBeforeNewTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string delayAfterNoTTS {
            get {
                return ((string)(this["delayAfterNoTTS"]));
            }
            set {
                this["delayAfterNoTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no text file selected")]
        public string saveTxtFilePath {
            get {
                return ((string)(this["saveTxtFilePath"]));
            }
            set {
                this["saveTxtFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveToggleReadTextFile {
            get {
                return ((bool)(this["saveToggleReadTextFile"]));
            }
            set {
                this["saveToggleReadTextFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool saveQueueSystem {
            get {
                return ((bool)(this["saveQueueSystem"]));
            }
            set {
                this["saveQueueSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QueueWithTypedText {
            get {
                return ((bool)(this["QueueWithTypedText"]));
            }
            set {
                this["QueueWithTypedText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WhisperFilterLog {
            get {
                return ((bool)(this["WhisperFilterLog"]));
            }
            set {
                this["WhisperFilterLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public string modHotkeyQuick {
            get {
                return ((string)(this["modHotkeyQuick"]));
            }
            set {
                this["modHotkeyQuick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J")]
        public string normalHotkeyQuick {
            get {
                return ((string)(this["normalHotkeyQuick"]));
            }
            set {
                this["normalHotkeyQuick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool forceMediaToggle {
            get {
                return ((bool)(this["forceMediaToggle"]));
            }
            set {
                this["forceMediaToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool shortcutStop {
            get {
                return ((bool)(this["shortcutStop"]));
            }
            set {
                this["shortcutStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool shortcutQuickType {
            get {
                return ((bool)(this["shortcutQuickType"]));
            }
            set {
                this["shortcutQuickType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool refocusWindow {
            get {
                return ((bool)(this["refocusWindow"]));
            }
            set {
                this["refocusWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string voiceWizardProKey {
            get {
                return ((string)(this["voiceWizardProKey"]));
            }
            set {
                this["voiceWizardProKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useVoiceWizardPro {
            get {
                return ((bool)(this["useVoiceWizardPro"]));
            }
            set {
                this["useVoiceWizardPro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool voiceWizProAzure {
            get {
                return ((bool)(this["voiceWizProAzure"]));
            }
            set {
                this["voiceWizProAzure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool voiceWizProAmazon {
            get {
                return ((bool)(this["voiceWizProAmazon"]));
            }
            set {
                this["voiceWizProAmazon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool voiceWizProMoonbase {
            get {
                return ((bool)(this["voiceWizProMoonbase"]));
            }
            set {
                this["voiceWizProMoonbase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool voiceWizProTranslation {
            get {
                return ((bool)(this["voiceWizProTranslation"]));
            }
            set {
                this["voiceWizProTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string uberDuckKey {
            get {
                return ((string)(this["uberDuckKey"]));
            }
            set {
                this["uberDuckKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string uberDuckSecret {
            get {
                return ((string)(this["uberDuckSecret"]));
            }
            set {
                this["uberDuckSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int labsModelID {
            get {
                return ((int)(this["labsModelID"]));
            }
            set {
                this["labsModelID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int labsOptimize {
            get {
                return ((int)(this["labsOptimize"]));
            }
            set {
                this["labsOptimize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int labsSimboost {
            get {
                return ((int)(this["labsSimboost"]));
            }
            set {
                this["labsSimboost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int labsStability {
            get {
                return ((int)(this["labsStability"]));
            }
            set {
                this["labsStability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveToWav {
            get {
                return ((bool)(this["saveToWav"]));
            }
            set {
                this["saveToWav"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TTS Characters Used: 0/0")]
        public string charsUsed {
            get {
                return ((string)(this["charsUsed"]));
            }
            set {
                this["charsUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Translation Characters Used: 0/0")]
        public string transCharsUsed {
            get {
                return ((string)(this["transCharsUsed"]));
            }
            set {
                this["transCharsUsed"] = value;
            }
        }
    }
}
